# Deployment file for product 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-product-dev
  labels:
    app: i27-product-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-product-dev
  template:
    metadata:
      labels:
        app: i27-product-dev
    spec:
      imagePullSecrets:
      - name: jfrog-registry
      containers:
      - name: i27-product-dev
        image: DIT # Image tag will be replaced by shared library
---
apiVersion: v1
kind: Service
metadata:
  name: i27-product-dev
  labels:
    app: i27-product-dev
spec:
  type: NodePort
  ports:
  - port: 8132
    targetPort: 8132
  selector:
    app: i27-product-dev 